
eureka:
  client:
    service-url:
      defaultZone: http://${properties.eureka.host}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
    name: dhcpregister.log
    path: /var/log/
    
properties:
  eureka:
    host: 10.18.0.2
  dhcp:
    config-file: /mnt/ramdisk/dhcpd.conf.registers
    
server:
  port: ${PORT:0}

spring:
  application:
    name: dhcpregister-production
